?par
set.seed(1234)
par(mar = c(0, 0, 0, 0))
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
dataFrame <- data.frame(x = x, y = y)
View(dataFrame)
distanceMatrix <- dist(dataFrame)
distanceMatrix
hClustering <- hclust(distanceMatrix)
plot(hClustering)
kmeansobj <- kmeans(x = dataFrame, centers = c(c(0,0),c(1,1),c(1,0)))
kmeansobj <- kmeans(x = dataFrame, centers = c(c(0,0),c(1,1),c(1,-1)))
?kmeans
?as.matrix
kmeans(x = dataFrame, centers = matrix(c(1,1,1,2),nrow = 2, ncol = 2))
kmeansobj <- kmeans(x = dataFrame, centers = matrix(c(1,1,1,2),nrow = 2, ncol = 2))
par(mar = rep(0.2, 4))
plot(x, y, col = kmeansobj$cluster, pch = 19, cex = 2)
points(kmeansobj$centers, col = 1:3, pch = 3, cex = 3, lwd = 3)
par(mar = rep(0.2, 4))
plot(x, y, col = kmeansobj$cluster, pch = 19, cex = 2)
points(kmeansobj$centers, col = 1:3, pch = 3, cex = 3, lwd = 3)
points(matrix(c(1,1,1,2),nrow = 2, ncol = 2), col = 1:3, pch = 4, cex = 3, lwd = 3)
kmeansobj <- kmeans(x = dataFrame, centers = matrix(c(2,1,1,2),nrow = 2, ncol = 2))
par(mar = rep(0.2, 4))
plot(x, y, col = kmeansobj$cluster, pch = 19, cex = 2)
points(kmeansobj$centers, col = 1:3, pch = 3, cex = 3, lwd = 3)
points(matrix(c(1,1,1,2),nrow = 2, ncol = 2), col = 1:3, pch = 4, cex = 3, lwd = 3)
